In [2]:
import numpy as np 

In [7]:
#Elemento neutro dentro de las matrices, producto interno a resolver << 
identidad = np.eye(4) 

In [3]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
vector = np.array([[2],[3],[5],[7]])

In [5]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [6]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [3]:
#Queremos calcular la inversa 
A = np.array([[1, 0, 1], [0, 1, 1], [-1, 1, 1]])

In [9]:
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [5]:
inversa_A = np.linalg.inv(A) 
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [6]:
print(A.dot(inversa_A))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
singular = np.array([[1, 1], [1, 1]]) 
print(singular)

[[1 1]
 [1 1]]


In [19]:
#Matrices cuadradas 
print(np.linalg.inv(singular))

LinAlgError: Singular matrix