In [1]:
import numpy as np 

In [2]:
escalar = 5.679 
vector = np.array([2, 3]) 
matriz = np.array([[1, 2],[3, 4], [5, 6]])


In [3]:
A = matriz * vector 

In [7]:
#Producto interno 
B = matriz.dot(vector)

In [8]:
#muy importante observen que:

#“producto interno” toma dos vectores y regresa un escalar.
#“producto externo” toma dos vectores y devuelve una matriz.(este no se menciono pero vale la pena lo revisen)

print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [6]:
print(B)

[ 8 18 28]


In [20]:
B = matriz.dot(vector) 
C = np.dot(matriz, vector)
print(B, C)

[ 8 18 28] [ 8 18 28]
