In [1]:
import numpy as np 

In [20]:
#Cercanos ceros como cero 
#Más fácil la identidad 

np.set_printoptions(suppress = True) 

In [6]:
A = np.array([[3, 1], [2, 1]]) 
print(A) 

[[3 1]
 [2 1]]


In [11]:
b = np.array([[1],[1]])

In [19]:
#Inversa de la matriz A 

inversa_A = np.linalg.inv(A) 
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [14]:
X = inversa_A.dot(b) 
print(X)

[[0.]
 [1.]]


In [22]:
print(A.dot(X))

[[1.]
 [1.]]


In [25]:
#Esto es solución de un sistema homogéneo 

sol_2 = inversa_A.dot(np.array([[3], [7]])) 
print(sol_2) 

[[-4.]
 [15.]]


In [26]:
print(A.dot(sol_2))

[[3.]
 [7.]]
