In [1]:
import numpy as np 

In [3]:
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])
C = np.array([[3,1], [4,2]])

In [4]:
#Asociativa 
ABC = A.dot(B.dot(C)) 
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [6]:
AB_C = A.dot(B).dot(C)
print(AB_C) 

[[ 60  26]
 [145  63]
 [295 129]]


In [8]:
#Distributiva 
D = A.dot(B + C)
E = (A.dot(B)) + (A.dot(C))

In [9]:
print(D) 
print(E) 

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [12]:
#Nota.
#El producto interno de matrices es:

#Asociativa: Sí
#Distributiva: Sí
#Conmutativa: NO
#El producto interno de vectores es:
#Asociativa: Sí
#Distributiva: Sí
#Conmutativa: Sí

#Igual
print(D == E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [13]:
F = B.dot(C)
G = C.dot(B)

In [14]:
print(F == G)

[[False False]
 [False False]]


In [17]:
print(F) 
print(G)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]


In [21]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]]) 

In [26]:
v1_tv2 = v1.T.dot(v2) 
v2_tv1 = v2.T.dot(v1) 

In [27]:
print(v1_tv2) 
print(v2_tv1)

[[41]]
[[41]]
