In [1]:
import numpy as np 

In [3]:
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])


In [9]:

print(A) 

[[ 2  3]
 [ 5  7]
 [11 13]]


In [10]:

print(B) 

[[1 3]
 [2 1]]


In [11]:
#Distributiva 
AB_t = A.dot(B).T 
B_tA_t = B.T.dot(A.T)

In [16]:
print(AB_t == B_tA_t)  
print(B_tA_t,"\n", AB_t) 

[[ True  True  True]
 [ True  True  True]]
[[ 8 19 37]
 [ 9 22 46]] 
 [[ 8 19 37]
 [ 9 22 46]]
