In [1]:
import numpy as np

In [2]:
escalar = 5.678
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
[[1,2,3,30],[4,5,6,31],[7,8,9,32]],
[[11,12,13,33],[14,15,16,34],[17,18,19,35]],
[[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])

In [4]:
#Sin filas y columnas
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [6]:
#Aquí no se ve el transponer salvo a realizar cuentas 
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [7]:
matriz_t = matriz.T
print (matriz_t)

[[1 3 5]
 [2 4 6]]


In [8]:
print(matriz_t.shape)

(2, 3)


In [9]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [10]:
print(tensor)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


In [11]:
#A^T = A
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
A = matriz 
B = matriz_t 

In [16]:
#!Longitud 
C = A + B 

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [18]:
B = np.array([[1,3],[3,4],[5,6]])
C = np.array([[6,5],[4,3],[2,1]]) 
C = A + B 
print(A) 
print(B) 
print(C) 


[[1 2]
 [3 4]
 [5 6]]
[[1 3]
 [3 4]
 [5 6]]
[[ 2  5]
 [ 6  8]
 [10 12]]


In [20]:
D = matriz + escalar 
print(D)

[[ 6.678  7.678]
 [ 8.678  9.678]
 [10.678 11.678]]
